name: Build & Push n8n-custom

on:
  workflow_dispatch:
    inputs:
      n8n_version:
        description: "n8n tag to build (e.g. 1.91.3)"
        required: true
  schedule:
    - cron: "0 3 * * 1"     # every Monday 03:00 UTC

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/n8n-extended

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write          # allow push to GHCR

    steps:
      # 1️⃣ Checkout source
      - uses: actions/checkout@v4

      # 2️⃣ Determine n8n base tag (manual input → default latest)
      - name: Set version
        id: vars
        run: echo "N8N_VER=${{ github.event.inputs.n8n_version || 'latest' }}" >> $GITHUB_OUTPUT

      # 3️⃣ Start Buildx builder (docker-container driver)
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true        # makes `docker buildx` the default

      # 4️⃣ Auth to GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5️⃣ Build & push with GHA cache
      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            N8N_VERSION=${{ steps.vars.outputs.N8N_VER }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.N8N_VER }}
            ${{ env.IMAGE_NAME }}:latest
          push: true
          cache-from: type=gha
          cache-to:   type=gha,mode=max
