name: Build & Push n8n-custom

on:
  workflow_dispatch:
    inputs:
      n8n_version:
        description: "n8n tag to build (e.g. 1.91.3)"
        required: true
  schedule:
    - cron: "0 3 * * 1"   # every Monday 03:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 1️⃣ Check out code
      - uses: actions/checkout@v4

      # 2️⃣ Gather variables ─ lowercase owner + n8n tag
      - name: Compute build vars
        id: vars
        shell: bash
        run: |
          OWNER_LC=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          echo "owner_lc=$OWNER_LC"   >> $GITHUB_OUTPUT
          echo "n8n_ver=${{ github.event.inputs.n8n_version || 'latest' }}" >> $GITHUB_OUTPUT

      # 3️⃣ Start BuildKit container driver
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      # 4️⃣ Log in to GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.vars.outputs.owner_lc }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5️⃣ Build, cache with GHA, and push tags
      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            N8N_VERSION=${{ steps.vars.outputs.n8n_ver }}
          tags: |
            ghcr.io/${{ steps.vars.outputs.owner_lc }}/n8n-extended:${{ steps.vars.outputs.n8n_ver }}
            ghcr.io/${{ steps.vars.outputs.owner_lc }}/n8n-extended:latest
          push: true
          cache-from: type=gha
          cache-to:   type=gha,mode=max
